### ISSUE TITLE
Failing count equality assertion of input and output

### ISSUE THREAD

**Issue by MohamedKari** [tobias-gp/SimpleFilters#1]
Hi,

setting the history to 1, I'd assume to get to have a short-term tracker that returns as many objects as it get's fed in the current time step and does not reintroduce objects from frames that were untracked once. 

Here's a test case:

![image](https://user-images.githubusercontent.com/29415552/90581410-71ad1280-e1cb-11ea-9966-9c46246a718d.png)

```python
class TestSingleStepSingleObjectTracking(TestCase):
    def setUp(self):
        strategy = PolynomialFilterStrategy()
        filter_prototype = Filter(strategy, history_size=1)
        self.tracker = Tracker(filter_prototype, distance_threshold=1.)
    
    def test_main(self):
        states = [
            np.array([1.0, 1.0]),
            np.array([1.5, 1.5]),
            np.array([2.0, 2.0]),
            np.array([3.0, 3.0]),
            np.array([3.5, 3.5]),
            np.array([4.0, 4.0])
        ]
        
        expected_tracking_ids = [0, 0, 0, 1, 1, 1]

        for i, (state, expected_tracking_id) in enumerate(zip(states, expected_tracking_ids)):
            print("timestep", i)
            self.tracker.update(state)
            tracked_state = self.tracker.get_tracked_objects()

            self.assertEqual(len(state), len(tracked_state))
            self.assertEqual(tracked_state[0].id, expected_tracking_id)
```

Thanks!

**Comment by tobias-gp** [comment]
Thanks @MohamedKari for raising this, there were a number of other problems that I could fix with your test case :) 

However, I want to explain why this is not the case with PolynomialFilterStrategy. Have a look at this picture: 
<img width="635" alt="grafik" src="https://user-images.githubusercontent.com/12759325/90598546-88675f80-e1f3-11ea-90d3-0bc200f7173b.png">

PolynomialFilterStrategy will predict the next location of your item (3 pred) based on polynomial regression. In your test case, the predicted location will be [2.5 2.5], while the incoming location is [3.0 3.0]. The distance is then 0,70 and the condition is met. DummyFilterStrategy however is not looking into the future, and simply returns the latest value.
